// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireDrawLock = `-- name: AcquireDrawLock :exec
SELECT pg_advisory_xact_lock(778899)
`

func (q *Queries) AcquireDrawLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquireDrawLock)
	return err
}

const countAssignments = `-- name: CountAssignments :one
SELECT count(*) FROM assignments
`

func (q *Queries) CountAssignments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (participant_id, team_id, round_number)
VALUES ($1, $2, $3)
RETURNING participant_id, team_id, round_number, created_at
`

type CreateAssignmentParams struct {
	ParticipantID int64 `json:"participant_id"`
	TeamID        int64 `json:"team_id"`
	RoundNumber   int32 `json:"round_number"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment, arg.ParticipantID, arg.TeamID, arg.RoundNumber)
	var i Assignment
	err := row.Scan(
		&i.ParticipantID,
		&i.TeamID,
		&i.RoundNumber,
		&i.CreatedAt,
	)
	return i, err
}

const getAssignmentWithTeam = `-- name: GetAssignmentWithTeam :one
SELECT a.participant_id, a.team_id, a.round_number, a.created_at,
       t.name        AS team_name,
       t.code        AS team_code,
       t.flag_url    AS team_flag_url,
       t.group_label AS team_group_label
FROM assignments a
JOIN teams t ON t.id = a.team_id
WHERE a.participant_id = $1
`

type GetAssignmentWithTeamRow struct {
	ParticipantID  int64              `json:"participant_id"`
	TeamID         int64              `json:"team_id"`
	RoundNumber    int32              `json:"round_number"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	TeamName       string             `json:"team_name"`
	TeamCode       pgtype.Text        `json:"team_code"`
	TeamFlagUrl    pgtype.Text        `json:"team_flag_url"`
	TeamGroupLabel pgtype.Text        `json:"team_group_label"`
}

func (q *Queries) GetAssignmentWithTeam(ctx context.Context, participantID int64) (GetAssignmentWithTeamRow, error) {
	row := q.db.QueryRow(ctx, getAssignmentWithTeam, participantID)
	var i GetAssignmentWithTeamRow
	err := row.Scan(
		&i.ParticipantID,
		&i.TeamID,
		&i.RoundNumber,
		&i.CreatedAt,
		&i.TeamName,
		&i.TeamCode,
		&i.TeamFlagUrl,
		&i.TeamGroupLabel,
	)
	return i, err
}

const listTeamPlayers = `-- name: ListTeamPlayers :many
SELECT a.team_id, p.name AS username
FROM assignments a
JOIN participants p ON p.id = a.participant_id
ORDER BY a.team_id, p.name
`

type ListTeamPlayersRow struct {
	TeamID   int64  `json:"team_id"`
	Username string `json:"username"`
}

func (q *Queries) ListTeamPlayers(ctx context.Context) ([]ListTeamPlayersRow, error) {
	rows, err := q.db.Query(ctx, listTeamPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamPlayersRow
	for rows.Next() {
		var i ListTeamPlayersRow
		if err := rows.Scan(&i.TeamID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickAvailableTeam = `-- name: PickAvailableTeam :one
SELECT id FROM teams
WHERE id NOT IN (SELECT team_id FROM assignments WHERE round_number = $1)
ORDER BY random()
LIMIT 1
`

func (q *Queries) PickAvailableTeam(ctx context.Context, roundNumber int32) (int64, error) {
	row := q.db.QueryRow(ctx, pickAvailableTeam, roundNumber)
	var id int64
	err := row.Scan(&id)
	return id, err
}
