// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fixtures.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listFixturesWithTeams = `-- name: ListFixturesWithTeams :many
SELECT f.id, f.api_fixture_id, f.stage, f.round_label, f.group_label,
       f.home_team_id, f.away_team_id, f.home_score, f.away_score,
       f.status, f.winner_team_id, f.kickoff_at,
       ht.name AS home_name, ht.code AS home_code, ht.flag_url AS home_flag,
       at.name AS away_name, at.code AS away_code, at.flag_url AS away_flag
FROM fixtures f
LEFT JOIN teams ht ON ht.id = f.home_team_id
LEFT JOIN teams at ON at.id = f.away_team_id
ORDER BY f.kickoff_at NULLS LAST, f.id
`

type ListFixturesWithTeamsRow struct {
	ID           int64              `json:"id"`
	ApiFixtureID int32              `json:"api_fixture_id"`
	Stage        string             `json:"stage"`
	RoundLabel   pgtype.Text        `json:"round_label"`
	GroupLabel   pgtype.Text        `json:"group_label"`
	HomeTeamID   pgtype.Int8        `json:"home_team_id"`
	AwayTeamID   pgtype.Int8        `json:"away_team_id"`
	HomeScore    pgtype.Int4        `json:"home_score"`
	AwayScore    pgtype.Int4        `json:"away_score"`
	Status       string             `json:"status"`
	WinnerTeamID pgtype.Int8        `json:"winner_team_id"`
	KickoffAt    pgtype.Timestamptz `json:"kickoff_at"`
	HomeName     pgtype.Text        `json:"home_name"`
	HomeCode     pgtype.Text        `json:"home_code"`
	HomeFlag     pgtype.Text        `json:"home_flag"`
	AwayName     pgtype.Text        `json:"away_name"`
	AwayCode     pgtype.Text        `json:"away_code"`
	AwayFlag     pgtype.Text        `json:"away_flag"`
}

func (q *Queries) ListFixturesWithTeams(ctx context.Context) ([]ListFixturesWithTeamsRow, error) {
	rows, err := q.db.Query(ctx, listFixturesWithTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFixturesWithTeamsRow
	for rows.Next() {
		var i ListFixturesWithTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApiFixtureID,
			&i.Stage,
			&i.RoundLabel,
			&i.GroupLabel,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomeScore,
			&i.AwayScore,
			&i.Status,
			&i.WinnerTeamID,
			&i.KickoffAt,
			&i.HomeName,
			&i.HomeCode,
			&i.HomeFlag,
			&i.AwayName,
			&i.AwayCode,
			&i.AwayFlag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFixture = `-- name: UpsertFixture :exec
INSERT INTO fixtures (api_fixture_id, stage, round_label, group_label,
                      home_team_id, away_team_id, home_score, away_score,
                      status, winner_team_id, kickoff_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now())
ON CONFLICT (api_fixture_id) DO UPDATE SET
  stage          = EXCLUDED.stage,
  round_label    = EXCLUDED.round_label,
  group_label    = EXCLUDED.group_label,
  home_team_id   = EXCLUDED.home_team_id,
  away_team_id   = EXCLUDED.away_team_id,
  home_score     = EXCLUDED.home_score,
  away_score     = EXCLUDED.away_score,
  status         = EXCLUDED.status,
  winner_team_id = EXCLUDED.winner_team_id,
  kickoff_at     = EXCLUDED.kickoff_at,
  updated_at     = now()
`

type UpsertFixtureParams struct {
	ApiFixtureID int32              `json:"api_fixture_id"`
	Stage        string             `json:"stage"`
	RoundLabel   pgtype.Text        `json:"round_label"`
	GroupLabel   pgtype.Text        `json:"group_label"`
	HomeTeamID   pgtype.Int8        `json:"home_team_id"`
	AwayTeamID   pgtype.Int8        `json:"away_team_id"`
	HomeScore    pgtype.Int4        `json:"home_score"`
	AwayScore    pgtype.Int4        `json:"away_score"`
	Status       string             `json:"status"`
	WinnerTeamID pgtype.Int8        `json:"winner_team_id"`
	KickoffAt    pgtype.Timestamptz `json:"kickoff_at"`
}

func (q *Queries) UpsertFixture(ctx context.Context, arg UpsertFixtureParams) error {
	_, err := q.db.Exec(ctx, upsertFixture,
		arg.ApiFixtureID,
		arg.Stage,
		arg.RoundLabel,
		arg.GroupLabel,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.HomeScore,
		arg.AwayScore,
		arg.Status,
		arg.WinnerTeamID,
		arg.KickoffAt,
	)
	return err
}
