// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppSetting struct {
	Key       string             `json:"key"`
	Value     pgtype.Text        `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.Int8        `json:"updated_by"`
}

type Assignment struct {
	ParticipantID int64              `json:"participant_id"`
	TeamID        int64              `json:"team_id"`
	RoundNumber   int32              `json:"round_number"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Fixture struct {
	ID           int64              `json:"id"`
	ApiFixtureID int32              `json:"api_fixture_id"`
	Stage        string             `json:"stage"`
	RoundLabel   pgtype.Text        `json:"round_label"`
	GroupLabel   pgtype.Text        `json:"group_label"`
	HomeTeamID   pgtype.Int8        `json:"home_team_id"`
	AwayTeamID   pgtype.Int8        `json:"away_team_id"`
	HomeScore    pgtype.Int4        `json:"home_score"`
	AwayScore    pgtype.Int4        `json:"away_score"`
	Status       string             `json:"status"`
	WinnerTeamID pgtype.Int8        `json:"winner_team_id"`
	KickoffAt    pgtype.Timestamptz `json:"kickoff_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Participant struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Standing struct {
	TeamID       int64              `json:"team_id"`
	GroupLabel   pgtype.Text        `json:"group_label"`
	Position     int32              `json:"position"`
	Played       int32              `json:"played"`
	Won          int32              `json:"won"`
	Draw         int32              `json:"draw"`
	Lost         int32              `json:"lost"`
	GoalsFor     int32              `json:"goals_for"`
	GoalsAgainst int32              `json:"goals_against"`
	GoalDiff     int32              `json:"goal_diff"`
	Points       int32              `json:"points"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SyncState struct {
	ID            int32              `json:"id"`
	LastSyncedAt  pgtype.Timestamptz `json:"last_synced_at"`
	TodayDone     bool               `json:"today_done"`
	ApiCallsToday int32              `json:"api_calls_today"`
	CallsDate     pgtype.Date        `json:"calls_date"`
	LastSuccessAt pgtype.Timestamptz `json:"last_success_at"`
	LastError     string             `json:"last_error"`
	LastErrorAt   pgtype.Timestamptz `json:"last_error_at"`
	LastWarnings  string             `json:"last_warnings"`
}

type Team struct {
	ID         int64       `json:"id"`
	ApiTeamID  pgtype.Int4 `json:"api_team_id"`
	Name       string      `json:"name"`
	Code       pgtype.Text `json:"code"`
	FlagUrl    pgtype.Text `json:"flag_url"`
	GroupLabel pgtype.Text `json:"group_label"`
}
