// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: participants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAssignments = `-- name: ClearAssignments :exec
DELETE FROM assignments
`

func (q *Queries) ClearAssignments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearAssignments)
	return err
}

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO participants (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateParticipant(ctx context.Context, name string) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipant, name)
	var i Participant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteParticipant = `-- name: DeleteParticipant :exec
DELETE FROM participants WHERE id = $1
`

func (q *Queries) DeleteParticipant(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteParticipant, id)
	return err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, name, created_at FROM participants WHERE id = $1
`

func (q *Queries) GetParticipant(ctx context.Context, id int64) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipant, id)
	var i Participant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listParticipants = `-- name: ListParticipants :many
SELECT p.id, p.name,
       a.team_id, a.round_number,
       t.name        AS team_name,
       t.code        AS team_code,
       t.flag_url    AS team_flag_url,
       t.group_label AS team_group_label
FROM participants p
LEFT JOIN assignments a ON a.participant_id = p.id
LEFT JOIN teams t ON t.id = a.team_id
ORDER BY p.name
`

type ListParticipantsRow struct {
	ID             int64       `json:"id"`
	Name           string      `json:"name"`
	TeamID         pgtype.Int8 `json:"team_id"`
	RoundNumber    pgtype.Int4 `json:"round_number"`
	TeamName       pgtype.Text `json:"team_name"`
	TeamCode       pgtype.Text `json:"team_code"`
	TeamFlagUrl    pgtype.Text `json:"team_flag_url"`
	TeamGroupLabel pgtype.Text `json:"team_group_label"`
}

func (q *Queries) ListParticipants(ctx context.Context) ([]ListParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listParticipants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantsRow
	for rows.Next() {
		var i ListParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamID,
			&i.RoundNumber,
			&i.TeamName,
			&i.TeamCode,
			&i.TeamFlagUrl,
			&i.TeamGroupLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
