// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcquireDrawLock(ctx context.Context) error
	ClearAssignments(ctx context.Context) error
	CountAssignments(ctx context.Context) (int64, error)
	CountTeams(ctx context.Context) (int64, error)
	CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error)
	CreateParticipant(ctx context.Context, name string) (Participant, error)
	DeleteParticipant(ctx context.Context, id int64) error
	GetAssignmentWithTeam(ctx context.Context, participantID int64) (GetAssignmentWithTeamRow, error)
	GetParticipant(ctx context.Context, id int64) (Participant, error)
	GetSetting(ctx context.Context, key string) (pgtype.Text, error)
	GetSyncState(ctx context.Context) (SyncState, error)
	InsertTeam(ctx context.Context, arg InsertTeamParams) (Team, error)
	ListFixturesWithTeams(ctx context.Context) ([]ListFixturesWithTeamsRow, error)
	ListParticipants(ctx context.Context) ([]ListParticipantsRow, error)
	ListStandings(ctx context.Context) ([]Standing, error)
	ListTeamPlayers(ctx context.Context) ([]ListTeamPlayersRow, error)
	ListTeams(ctx context.Context) ([]Team, error)
	PickAvailableTeam(ctx context.Context, roundNumber int32) (int64, error)
	RecordSyncError(ctx context.Context, arg RecordSyncErrorParams) error
	RecordSyncSuccess(ctx context.Context, arg RecordSyncSuccessParams) error
	SetTeamApiInfo(ctx context.Context, arg SetTeamApiInfoParams) error
	SetTeamGroup(ctx context.Context, arg SetTeamGroupParams) error
	UpdateSyncState(ctx context.Context, arg UpdateSyncStateParams) error
	UpsertFixture(ctx context.Context, arg UpsertFixtureParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertStanding(ctx context.Context, arg UpsertStandingParams) error
}

var _ Querier = (*Queries)(nil)
