// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSetting = `-- name: GetSetting :one
SELECT value FROM app_settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value pgtype.Text
	err := row.Scan(&value)
	return value, err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO app_settings (key, value, updated_by, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (key) DO UPDATE
  SET value = EXCLUDED.value, updated_by = EXCLUDED.updated_by, updated_at = now()
`

type UpsertSettingParams struct {
	Key       string      `json:"key"`
	Value     pgtype.Text `json:"value"`
	UpdatedBy pgtype.Int8 `json:"updated_by"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting, arg.Key, arg.Value, arg.UpdatedBy)
	return err
}
