// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: standings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listStandings = `-- name: ListStandings :many
SELECT team_id, group_label, position, played, won, draw, lost, goals_for, goals_against, goal_diff, points, updated_at FROM standings
`

func (q *Queries) ListStandings(ctx context.Context) ([]Standing, error) {
	rows, err := q.db.Query(ctx, listStandings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Standing
	for rows.Next() {
		var i Standing
		if err := rows.Scan(
			&i.TeamID,
			&i.GroupLabel,
			&i.Position,
			&i.Played,
			&i.Won,
			&i.Draw,
			&i.Lost,
			&i.GoalsFor,
			&i.GoalsAgainst,
			&i.GoalDiff,
			&i.Points,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStanding = `-- name: UpsertStanding :exec
INSERT INTO standings (team_id, group_label, position, played, won, draw, lost,
                       goals_for, goals_against, goal_diff, points, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now())
ON CONFLICT (team_id) DO UPDATE SET
  group_label   = EXCLUDED.group_label,
  position      = EXCLUDED.position,
  played        = EXCLUDED.played,
  won           = EXCLUDED.won,
  draw          = EXCLUDED.draw,
  lost          = EXCLUDED.lost,
  goals_for     = EXCLUDED.goals_for,
  goals_against = EXCLUDED.goals_against,
  goal_diff     = EXCLUDED.goal_diff,
  points        = EXCLUDED.points,
  updated_at    = now()
`

type UpsertStandingParams struct {
	TeamID       int64       `json:"team_id"`
	GroupLabel   pgtype.Text `json:"group_label"`
	Position     int32       `json:"position"`
	Played       int32       `json:"played"`
	Won          int32       `json:"won"`
	Draw         int32       `json:"draw"`
	Lost         int32       `json:"lost"`
	GoalsFor     int32       `json:"goals_for"`
	GoalsAgainst int32       `json:"goals_against"`
	GoalDiff     int32       `json:"goal_diff"`
	Points       int32       `json:"points"`
}

func (q *Queries) UpsertStanding(ctx context.Context, arg UpsertStandingParams) error {
	_, err := q.db.Exec(ctx, upsertStanding,
		arg.TeamID,
		arg.GroupLabel,
		arg.Position,
		arg.Played,
		arg.Won,
		arg.Draw,
		arg.Lost,
		arg.GoalsFor,
		arg.GoalsAgainst,
		arg.GoalDiff,
		arg.Points,
	)
	return err
}
