// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_state.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncState = `-- name: GetSyncState :one
SELECT id, last_synced_at, today_done, api_calls_today, calls_date, last_success_at, last_error, last_error_at, last_warnings FROM sync_state WHERE id = 1
`

func (q *Queries) GetSyncState(ctx context.Context) (SyncState, error) {
	row := q.db.QueryRow(ctx, getSyncState)
	var i SyncState
	err := row.Scan(
		&i.ID,
		&i.LastSyncedAt,
		&i.TodayDone,
		&i.ApiCallsToday,
		&i.CallsDate,
		&i.LastSuccessAt,
		&i.LastError,
		&i.LastErrorAt,
		&i.LastWarnings,
	)
	return i, err
}

const recordSyncError = `-- name: RecordSyncError :exec
UPDATE sync_state
SET last_error    = $1,
    last_error_at = $2
WHERE id = 1
`

type RecordSyncErrorParams struct {
	LastError   string             `json:"last_error"`
	LastErrorAt pgtype.Timestamptz `json:"last_error_at"`
}

func (q *Queries) RecordSyncError(ctx context.Context, arg RecordSyncErrorParams) error {
	_, err := q.db.Exec(ctx, recordSyncError, arg.LastError, arg.LastErrorAt)
	return err
}

const recordSyncSuccess = `-- name: RecordSyncSuccess :exec
UPDATE sync_state
SET last_success_at = $1,
    last_error      = '',
    last_warnings   = $2
WHERE id = 1
`

type RecordSyncSuccessParams struct {
	LastSuccessAt pgtype.Timestamptz `json:"last_success_at"`
	LastWarnings  string             `json:"last_warnings"`
}

func (q *Queries) RecordSyncSuccess(ctx context.Context, arg RecordSyncSuccessParams) error {
	_, err := q.db.Exec(ctx, recordSyncSuccess, arg.LastSuccessAt, arg.LastWarnings)
	return err
}

const updateSyncState = `-- name: UpdateSyncState :exec
UPDATE sync_state
SET last_synced_at = $1,
    today_done      = $2,
    api_calls_today = $3,
    calls_date      = $4
WHERE id = 1
`

type UpdateSyncStateParams struct {
	LastSyncedAt  pgtype.Timestamptz `json:"last_synced_at"`
	TodayDone     bool               `json:"today_done"`
	ApiCallsToday int32              `json:"api_calls_today"`
	CallsDate     pgtype.Date        `json:"calls_date"`
}

func (q *Queries) UpdateSyncState(ctx context.Context, arg UpdateSyncStateParams) error {
	_, err := q.db.Exec(ctx, updateSyncState,
		arg.LastSyncedAt,
		arg.TodayDone,
		arg.ApiCallsToday,
		arg.CallsDate,
	)
	return err
}
