// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTeams = `-- name: CountTeams :one
SELECT count(*) FROM teams
`

func (q *Queries) CountTeams(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTeams)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertTeam = `-- name: InsertTeam :one
INSERT INTO teams (name, code, flag_url, group_label, api_team_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, api_team_id, name, code, flag_url, group_label
`

type InsertTeamParams struct {
	Name       string      `json:"name"`
	Code       pgtype.Text `json:"code"`
	FlagUrl    pgtype.Text `json:"flag_url"`
	GroupLabel pgtype.Text `json:"group_label"`
	ApiTeamID  pgtype.Int4 `json:"api_team_id"`
}

func (q *Queries) InsertTeam(ctx context.Context, arg InsertTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, insertTeam,
		arg.Name,
		arg.Code,
		arg.FlagUrl,
		arg.GroupLabel,
		arg.ApiTeamID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.ApiTeamID,
		&i.Name,
		&i.Code,
		&i.FlagUrl,
		&i.GroupLabel,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, api_team_id, name, code, flag_url, group_label FROM teams ORDER BY group_label, name
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.ApiTeamID,
			&i.Name,
			&i.Code,
			&i.FlagUrl,
			&i.GroupLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTeamApiInfo = `-- name: SetTeamApiInfo :exec
UPDATE teams
SET api_team_id = $2,
    flag_url    = COALESCE($3, flag_url)
WHERE id = $1
`

type SetTeamApiInfoParams struct {
	ID        int64       `json:"id"`
	ApiTeamID pgtype.Int4 `json:"api_team_id"`
	FlagUrl   pgtype.Text `json:"flag_url"`
}

func (q *Queries) SetTeamApiInfo(ctx context.Context, arg SetTeamApiInfoParams) error {
	_, err := q.db.Exec(ctx, setTeamApiInfo, arg.ID, arg.ApiTeamID, arg.FlagUrl)
	return err
}

const setTeamGroup = `-- name: SetTeamGroup :exec
UPDATE teams SET group_label = $2 WHERE id = $1
`

type SetTeamGroupParams struct {
	ID         int64       `json:"id"`
	GroupLabel pgtype.Text `json:"group_label"`
}

func (q *Queries) SetTeamGroup(ctx context.Context, arg SetTeamGroupParams) error {
	_, err := q.db.Exec(ctx, setTeamGroup, arg.ID, arg.GroupLabel)
	return err
}
